// Code generated by Slice Machine. DO NOT EDIT.
//
// This file is normally regenerated automatically whenever you run
// `npx slicemachine` against your live Prismic repository. It is checked in
// here by hand so the template type-checks before you've connected a repo —
// once you run Slice Machine for real, let it overwrite this file.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/** Content for Homepage documents */
interface HomepageDocumentData {
  meta_title: prismic.KeyTextField;
  meta_description: prismic.KeyTextField;
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>;
}

type HomepageDocumentDataSlicesSlice = ProjectGridSlice;

export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

/** Content for Settings documents */
interface SettingsDocumentData {
  site_title: prismic.KeyTextField;
  meta_description: prismic.KeyTextField;
  signature_mark: prismic.ImageField<never>;
  email: prismic.KeyTextField;
  instagram_url: prismic.LinkField;
}

export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

/** Item in Project → Gallery */
export interface ProjectDocumentDataGalleryItem {
  image: prismic.ImageField<never>;
}

/** Content for Project documents */
interface ProjectDocumentData {
  name: prismic.KeyTextField;
  category: prismic.SelectField<"Wedding" | "Editorial">;
  couple_name: prismic.KeyTextField;
  wedding_date: prismic.DateField;
  location: prismic.KeyTextField;
  info: prismic.RichTextField;
  cover_image: prismic.ImageField<never>;
  gallery: prismic.GroupField<Simplify<ProjectDocumentDataGalleryItem>>;
  sort_order: prismic.NumberField;
  meta_title: prismic.KeyTextField;
  meta_description: prismic.KeyTextField;
}

export type ProjectDocument<Lang extends string = string> =
  prismic.PrismicDocument<Simplify<ProjectDocumentData>, "project", Lang>;

/** Content for About documents */
interface AboutDocumentData {
  portrait: prismic.ImageField<never>;
  bio: prismic.RichTextField;
  meta_title: prismic.KeyTextField;
  meta_description: prismic.KeyTextField;
}

export type AboutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<AboutDocumentData>,
    "about",
    Lang
  >;

/** Content for Contact documents */
interface ContactDocumentData {
  intro: prismic.RichTextField;
  meta_title: prismic.KeyTextField;
  meta_description: prismic.KeyTextField;
}

export type ContactDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ContactDocumentData>,
    "contact",
    Lang
  >;

export type AllDocumentTypes =
  | HomepageDocument
  | SettingsDocument
  | ProjectDocument
  | AboutDocument
  | ContactDocument;

/** Primary content in ProjectGrid → default → Primary */
export interface ProjectGridSliceDefaultPrimary {
  eyebrow: prismic.KeyTextField;
}

/** Default variation for ProjectGrid Slice */
export type ProjectGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectGridSliceDefaultPrimary>,
  never
>;

/** ProjectGrid Shared Slice — pulls all Project documents live and renders
 *  the looping homepage list. */
export type ProjectGridSliceVariation = ProjectGridSliceDefault;

export type ProjectGridSlice = prismic.SharedSlice<
  "project_grid",
  ProjectGridSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      ProjectDocument,
      ProjectDocumentData,
      ProjectDocumentDataGalleryItem,
      AboutDocument,
      AboutDocumentData,
      ContactDocument,
      ContactDocumentData,
      AllDocumentTypes,
      ProjectGridSlice,
      ProjectGridSliceDefaultPrimary,
      ProjectGridSliceVariation,
      ProjectGridSliceDefault,
    };
  }
}
